service: default
runtime: nodejs18

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /.*
    script: auto
    redirect_http_response_code: 301
    secure: always

  - url: /
    static_dir: stg-files

env_variables:
  NUXT_HOST: "0.0.0.0"
  NUXT_PORT: "8080"
  NODE_ENV: "production"
